---
name: Execute Admin Asynchronous Job

on:
  workflow_call:
    inputs:
      SYNAPSE_HOST:
        required: true
        type: string
        description: The Synapse host to target
      ASYNC_JOB_PAYLOAD:
        required: true
        type: string
        description: The payload to pass to the async job, in JSON format

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        env:
          SYNAPSE_HOST: ${{ inputs.SYNAPSE_HOST }}
          ASYNC_JOB_PAYLOAD: ${{ inputs.ASYNC_JOB_PAYLOAD }}
        run: |
          COMMAND_TO_EXECUTE="scripts/execute_admin_async_job.sh $SYNAPSE_HOST '$ASYNC_JOB_PAYLOAD'"
          PIPELINE_PARAMETERS="CommandToExecute=\"$COMMAND_TO_EXECUTE\""
          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
